package com.wechart.core.mapper;

import com.wechart.bean.po.ChattingRobotKnowledge;
import com.wechart.bean.po.ChattingRobotKnowledgeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ChattingRobotKnowledgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int countByExample(ChattingRobotKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int deleteByExample(ChattingRobotKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    @Delete({
        "delete from chatting_robot_knowledge",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    @Insert({
        "insert into chatting_robot_knowledge (question, answer, ",
        "category)",
        "values (#{question,jdbcType=VARCHAR}, #{answer,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ChattingRobotKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int insertSelective(ChattingRobotKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    List<ChattingRobotKnowledge> selectByExample(ChattingRobotKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    @Select({
        "select",
        "id, question, answer, category",
        "from chatting_robot_knowledge",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ChattingRobotKnowledge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") ChattingRobotKnowledge record, @Param("example") ChattingRobotKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int updateByExample(@Param("record") ChattingRobotKnowledge record, @Param("example") ChattingRobotKnowledgeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    int updateByPrimaryKeySelective(ChattingRobotKnowledge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatting_robot_knowledge
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    @Update({
        "update chatting_robot_knowledge",
        "set question = #{question,jdbcType=VARCHAR},",
          "answer = #{answer,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ChattingRobotKnowledge record);
}