package com.wechart.bean.po;

public class ChattingRobotKnowledge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_robot_knowledge.id
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_robot_knowledge.question
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_robot_knowledge.answer
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatting_robot_knowledge.category
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_robot_knowledge.id
     *
     * @return the value of chatting_robot_knowledge.id
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_robot_knowledge.id
     *
     * @param id the value for chatting_robot_knowledge.id
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_robot_knowledge.question
     *
     * @return the value of chatting_robot_knowledge.question
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_robot_knowledge.question
     *
     * @param question the value for chatting_robot_knowledge.question
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_robot_knowledge.answer
     *
     * @return the value of chatting_robot_knowledge.answer
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_robot_knowledge.answer
     *
     * @param answer the value for chatting_robot_knowledge.answer
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatting_robot_knowledge.category
     *
     * @return the value of chatting_robot_knowledge.category
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatting_robot_knowledge.category
     *
     * @param category the value for chatting_robot_knowledge.category
     *
     * @mbggenerated Wed Sep 28 12:14:23 CST 2016
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}